version: 0.1
phases:
    build:
        commands:
          - aws configure set region us-east-1 
          - aws configure set aws_access_key_id ${ACCESS_KEY}
          - aws configure set aws_secret_access_key ${ACCESS_SECRET}
    install:
        commands:
          - aws cloudformation package --template-file template.yaml --s3-bucket stockx-lamdba --output-template-file output-template.yaml
artifacts:
    type: zip
    files:
      - template.yaml
      - output-template.yaml